services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hydra_game
      - PORT=5000
      - DEBUG=true
    command: sh -c "echo '🐳 Starting Hydra Game...' && echo '🚀 Running migrations...' && pnpm db:push && echo '✅ Starting dev server...' && pnpm dev"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hydra-network
    restart: unless-stopped

  # PostgreSQL database
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hydra_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - hydra-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hydra_game"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  hydra-network:
    driver: bridge