services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - hydra-network
    restart: unless-stopped

  # PostgreSQL database (opcional, para quando quiser usar ao invés de in-memory)
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hydra_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hydra-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  hydra-network:
    driver: bridge